on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - .github/workflows/cargo-test.yml
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
  pull_request:
    paths:
      - '**.rs'
      - .github/workflows/cargo-test.yml
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
  workflow_dispatch:
permissions: read-all
name: cargo test
jobs:
  cargotest:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          log-level: warn
          command: check bans licenses sources
          arguments: --all-features
