on:
  push:
    branches:
      - main
    paths:
      - 'compiler/**.rs'
      - compiler/.github/workflows/cargo-test.yml
      - compiler/Cargo.lock
      - compiler/Cargo.toml
      - compiler/rust-toolchain.toml
  pull_request:
    paths:
      - 'compiler/**.rs'
      - compiler/.github/workflows/cargo-test.yml
      - compiler/Cargo.lock
      - compiler/Cargo.toml
      - compiler/rust-toolchain.toml
  workflow_dispatch:
permissions: read-all
name: cargo test
jobs:
  compiler-cargotest:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - uses: taiki-e/install-action@nextest

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1

      - name: cargo test
        shell: bash
        run: |
          cargo nextest run --all-features
        env:
          RUST_BACKTRACE: 1
