on:
  push:
    branches:
      - main
    paths:
      - 'compiler/**.rs'
      - compiler/.github/workflows/cargo-clippy.yml
      - compiler/Cargo.lock
      - compiler/Cargo.toml
      - compiler/rust-toolchain.toml
  pull_request:
    paths:
      - 'compiler/**.rs'
      - compiler/.github/workflows/cargo-clippy.yml
      - compiler/Cargo.lock
      - compiler/Cargo.toml
      - compiler/rust-toolchain.toml
name: cargo clippy
jobs:
  compiler-cargoclippy:
    name: cargo clippy --tests --benches --examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: "--benches --tests --examples --all-features -- -D warnings"
